[group('qa')]
build:
    uv build --package base

[group('qa')]
test:
    uv run --package base pytest . || test $? -eq 5

[group('qa')]
lint:
    uv run ruff check .
    uv run ruff format --check .
