[group('qa')]
build:
    uv build --package market_data

[group('qa')]
test:
    uv run --package market_data pytest . || test $? -eq 5

[group('qa')]
lint:
    uv run ruff check .
    uv run ruff format --check .
