name: Service CI

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - uses: extractions/setup-just@v3
      - run: uv sync --extra dev
      - run: just "${{ inputs.service }}" lint

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13", "3.14"]
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - uses: extractions/setup-just@v3
      - uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
      - run: uv sync --extra dev
      - run: just "${{ inputs.service }}" test
